import { test, expect } from "@playwright/test";
import { waitForMapGeneration } from "./helpers/fmg-helpers";

test.describe("Burgs.add", () => {
  test.beforeEach(async ({ context, page }) => {
    await context.clearCookies();

    await page.goto("/");
    await page.evaluate(() => {
      localStorage.clear();
      sessionStorage.clear();
    });

    // Navigate with seed parameter and wait for full load
    await page.goto("/?seed=test-burgs&width=1280&height=720");

    // Wait for map generation to complete
    await waitForMapGeneration(page);

    // Additional wait for any rendering/animations to settle
    await page.waitForTimeout(500);
  });

  test("should create burg with falsy port value when not on coast", async ({
    page,
  }) => {
    const result = await page.evaluate(() => {
      const { cells, burgs } = window.fmg.world.pack;

      // Find an existing inland burg (generated by the world, not on coast)
      for (let b = 1; b < burgs.length; b++) {
        const burg = burgs[b];
        if (!burg || burg.removed) continue;
        const cell = burg.cell;
        const isLand = cells.h[cell] >= 20;
        const hasNoHarbor = !cells.harbor[cell];
        if (isLand && hasNoHarbor) {
          return {
            burgId: b,
            port: burg.port,
            portType: typeof burg.port,
            portIsFalsy: !burg.port,
            x: burg.x,
            y: burg.y,
          };
        }
      }

      return { error: "No inland burg found" };
    });

    expect(result.error).toBeUndefined();
    // Port should be 0 (number), not "0" (string) for inland burgs
    expect(result.port).toBe(0);
    expect(result.portType).toBe("number");
    expect(result.portIsFalsy).toBe(true);
    // Explicitly verify it's not the buggy string "0"
    expect(result.port).not.toBe("0");
  });

  test("port toggle button should be inactive for non-coastal burg", async ({
    page,
  }) => {
    // Find an existing inland burg using world state
    const burgId = await page.evaluate(() => {
      const { cells, burgs } = window.fmg.world.pack;

      for (let b = 1; b < burgs.length; b++) {
        const burg = burgs[b];
        if (!burg || burg.removed) continue;
        const cell = burg.cell;
        const isLand = cells.h[cell] >= 20;
        const hasNoHarbor = !cells.harbor[cell];
        if (isLand && hasNoHarbor) {
          return b;
        }
      }
      return null;
    });

    expect(burgId).not.toBeNull();

    // Open the burg editor by clicking its icon in the SVG
    const burgIconSelector = `[id="burg${burgId}"]`;
    await page.click(burgIconSelector);

    // Wait for the editor dialog to appear
    await page.waitForSelector("#burgEditor", { state: "visible" });

    // The port toggle button should have the "inactive" class
    const portButton = page.locator("#burgPort");
    await expect(portButton).toHaveClass(/inactive/);
  });
});
