import "../versioning";
import "../components";
import "../config";
import { initLayers } from "./layers";
import "./style";
import "./editors";
import "../editors/coastline-editor";
import "./elevation-profile";
import "../editors/namesbase-editor";
import "../io";
import "../utils/uiHelpers";
import { initHotkeys } from "./hotkeys";
import "./measurers";
import "../editors/biomes-editor";
import "../editors/zones-editor";
import "../editors/markers-editor";
import "../editors/lakes-editor";
import "../editors/rivers-editor";
import "../editors/routes-editor";
import "../editors/notes-editor";
import "./tools";
import { initOptions } from "./options";
import "../editors/heightmap-editor";
import "../editors/provinces-editor";
import "./routes-overview";
import "./rivers-overview";
import "./markers-overview";
import "./regiments-overview";
import "./temperature-graph";
import "./world-configurator";
import "./submap-tool";
import "../editors/route-group-editor";
import "../editors/ice-editor";
import "./transform-tool";
import "./rivers-creator";
import "./ai-generator";
import "./minimap";
import "../editors/units-editor";
import "../editors/relief-editor";
import "../editors/burg-group-editor";
import "../editors/labels-editor";
import "../editors/burg-editor";
import "../editors/regiment-editor";
import "../editors/emblems-editor";
import "./military-overview";
import "../editors/diplomacy-editor";
import "./burgs-overview";
import "./battle-screen";
import "./3d";

export function initControllers(): void {
  initLayers();
  initHotkeys();
  initOptions();
}
