import type { MilitaryRegiment } from "../../hostTypes";
import { P } from "../../hostUtils";
import { getWorldContext } from "../nobilityContext";
import { Characters } from "./characters-generator";
import type { Character } from "./characterTypes";

/** Titles that mark a character as an active field/fleet commander, as opposed to a central government office. */
const COMMANDER_TITLES: readonly string[] = ["Commander", "Admiral"];

/** Chance that any single eligible regiment gets a dedicated officer per pass — officers are the exception, not the rule. */
const OFFICER_ASSIGNMENT_CHANCE = 0.35;

function isActiveCommander(character: Character | undefined, stateId: number): character is Character {
  if (!character || character.dead) return false;
  return character.titles.some(
    t => t.entityType === "state" && t.entityId === stateId && COMMANDER_TITLES.includes(t.title)
  );
}

/**
 * Resolves the living officer actually in command of `regiment`, ignoring a stale
 * `commanderId` left behind by death, resignation, or a full military regeneration that
 * rebuilt the regiment array from scratch (see assignOfficers() below).
 */
export function getRegimentCommander(characters: Character[], regiment: MilitaryRegiment): Character | undefined {
  if (regiment.commanderId === undefined) return undefined;
  const officer = characters.find(c => c.i === regiment.commanderId);
  return isActiveCommander(officer, regiment.state) ? officer : undefined;
}

/**
 * Sparsely assigns field/fleet officers to regiments. The capital guard is always led by
 * the state's own Marshal (a central office already generated by Characters.generate())
 * rather than a new character — it is the crown's household troops, not an independent
 * command. Every other regiment (field army, vassal garrison, fleet) has a small, per-pass
 * chance of getting a dedicated officer with above-average martial skill.
 *
 * Safe to call repeatedly (every simulation tick, every manual regenerate): regiments that
 * already have a living, titled commander are left untouched, so this only ever fills
 * vacancies — from a fresh regiment array after Military.generate() reruns, or from an
 * officer dying/resigning during Characters.advanceAge().
 */
export function assignOfficers(): void {
  const { pack } = getWorldContext();
  const characters = pack.characters;
  if (!characters || !pack.states?.length) return;

  const states = pack.states.filter(s => s.i && !s.removed);

  for (const state of states) {
    if (!state.military?.length) continue;

    const marshal = characters.find(
      c => !c.dead && c.titles.some(t => t.entityType === "state" && t.entityId === state.i && t.title === "Marshal")
    );

    for (const regiment of state.military) {
      if (getRegimentCommander(characters, regiment)) continue;

      if (regiment.isCapitalGuard) {
        if (marshal) regiment.commanderId = marshal.i;
        continue;
      }

      if (!P(OFFICER_ASSIGNMENT_CHANCE)) continue;

      const title = regiment.n ? "Admiral" : "Commander";
      const officer = Characters.createOfficer(state, title);
      regiment.commanderId = officer.i;
    }
  }
}
