import type { Character } from "../../characters/characterTypes";
import type { MilitaryRegiment } from "../../hostTypes";
import { P } from "../../hostUtils";
import { getWorldContext } from "../nobilityContext";
import { Characters } from "./characterLifecycle";

/** Titles that mark a character as an active field/fleet commander, as opposed to a central government office. */
const COMMANDER_TITLES: readonly string[] = ["Commander", "Admiral", "Marshal"];

/** Chance that any single eligible regiment gets a dedicated officer per pass — officers are the exception, not the rule. */
const OFFICER_ASSIGNMENT_CHANCE = 0.35;

/**
 * Minimum current troop strength for a dedicated Commander/Admiral. Frontier generation
 * often leaves a second burg with a ~15–20-head provincial company; those platoons stay
 * under the Marshal (or untitled) instead of minting an officer whose stipend floor
 * (`FIELD_COMMANDER_STIPEND_FLOOR`, 1.5 SP/cycle) would bankrupt a small-realm treasury.
 * Company-scale forces (~80+) are a real independent command.
 */
export const MIN_TROOPS_FOR_DEDICATED_OFFICER = 80;

/** Living troop count used to decide whether a field/fleet unit is a real command. */
export function regimentTroopStrength(regiment: Pick<MilitaryRegiment, "a" | "u">): number {
  if (typeof regiment.a === "number" && Number.isFinite(regiment.a)) {
    return Math.max(0, regiment.a);
  }
  let fromUnits = 0;
  for (const count of Object.values(regiment.u || {})) {
    fromUnits += Number(count) || 0;
  }
  return Math.max(0, fromUnits);
}

/**
 * True when a non-guard regiment is large enough to receive (and be paid as) a
 * dedicated field or fleet officer. Capital guards are always Marshal-led.
 */
export function regimentQualifiesForDedicatedOfficer(
  regiment: Pick<MilitaryRegiment, "a" | "u" | "isCapitalGuard">
): boolean {
  if (regiment.isCapitalGuard) return false;
  return regimentTroopStrength(regiment) >= MIN_TROOPS_FOR_DEDICATED_OFFICER;
}

function isActiveCommander(character: Character | undefined, stateId: number): character is Character {
  if (!character || character.dead) return false;
  return character.titles.some(
    t => t.entityType === "state" && t.entityId === stateId && COMMANDER_TITLES.includes(t.title)
  );
}

/**
 * Resolves the living officer actually in command of `regiment`, ignoring a stale
 * `commanderId` left behind by death, resignation, or a full military regeneration that
 * rebuilt the regiment array from scratch (see assignOfficers() below).
 */
export function getRegimentCommander(characters: Character[], regiment: MilitaryRegiment): Character | undefined {
  if (regiment.commanderId === undefined) return undefined;
  const officer = characters.find(c => c.i === regiment.commanderId);
  return isActiveCommander(officer, regiment.state) ? officer : undefined;
}

/**
 * Sparsely assigns field/fleet officers to regiments. The capital guard is always led by
 * the state's own Marshal (a central office already generated by Characters.generate())
 * rather than a new character — it is the crown's household troops, not an independent
 * command. Every other regiment that qualifies as a company-scale field army, vassal
 * garrison, or fleet has a small, per-pass chance of getting a dedicated officer with
 * above-average martial skill. Sub-company remnants are left untitled.
 *
 * Safe to call repeatedly (every simulation tick, every manual regenerate): regiments that
 * already have a living, titled commander are left untouched, so this only ever fills
 * vacancies — from a fresh regiment array after Military.generate() reruns, or from an
 * officer dying/resigning during Characters.advanceAge().
 */
export function assignOfficers(): void {
  const { pack } = getWorldContext();
  const characters = pack.characters;
  if (!characters || !pack.states?.length) return;

  const states = pack.states.filter(s => s.i && !s.removed);

  for (const state of states) {
    if (!state.military?.length) continue;

    const marshal = characters.find(
      c => !c.dead && c.titles.some(t => t.entityType === "state" && t.entityId === state.i && t.title === "Marshal")
    );

    for (const regiment of state.military) {
      if (getRegimentCommander(characters, regiment)) continue;

      if (regiment.isCapitalGuard) {
        if (marshal) regiment.commanderId = marshal.i;
        continue;
      }

      if (!regimentQualifiesForDedicatedOfficer(regiment)) continue;
      if (!P(OFFICER_ASSIGNMENT_CHANCE)) continue;

      const title = regiment.n ? "Admiral" : "Commander";
      const officer = Characters.createOfficer(state, title);
      regiment.commanderId = officer.i;
    }
  }
}
