// Override d3 BaseType to any so legacy d3 callbacks don't require explicit this typing
// Augment d3 Selection to allow any-typed 'this' in callbacks for legacy code
declare module "d3-selection" {
	interface Selection<GElement, Datum, PElement, PDatum> {
		each(func: (this: any, d: Datum, i: number, groups: GElement[] | ArrayLike<GElement>) => void): this;
		filter(value: (this: any, d: Datum, i: number, groups: GElement[] | ArrayLike<GElement>) => boolean): Selection<GElement, Datum, PElement, PDatum>;
	}
}

type AnyFn = (...args: any[]) => any;
type LegacyCheckboxControl = {checked: boolean};
type LegacyValueControl = {value: string};
type LegacyControlElement = HTMLElement & {
	value: any;
	min: any;
	max: any;
	step: any;
	checked: any;
	files: any;
	options: HTMLOptionsCollection | any;
	selectedOptions: HTMLCollectionOf<HTMLOptionElement> | any;
	add: (item: HTMLOptionElement, before?: HTMLOptionElement | number | null) => void;
	disabled: boolean;
	click: () => void;
	width: any;
	height: any;
	getScreenCTM: () => DOMMatrix | null;
	dataset: DOMStringMap;
	style: CSSStyleDeclaration;
};
type LegacyOptions = Record<string, any>;
type LegacyLdb = {
	get: (key: string) => Promise<Blob | null>;
	set: (key: string, value: Blob | string) => Promise<unknown> | void;
};

declare global {
interface Window {
	Cloud: any;
	Dropbox: any;
	tinymce: any;
	edits: any;
	chrome: any;
	ThreeD: any;
	THREE: any;
	loopSubdivision: any;
	drawFeatures: () => void;
	getFileName: (name?: string) => string;
	downloadFile: (content: string | Blob, name: string, type?: string) => void;
	fog: (id: string, path: string) => void;
	unfog: (id?: string) => void;
	locked: (settingId: string) => boolean;
}

interface Element {
	value: any;
	checked: any;
	options: any;
	files: any;
	disabled: any;
	innerHTML: any;
	textContent: any;
	type: any;
	dataset: DOMStringMap;
	style: CSSStyleDeclaration;
	points: any;
	getTotalLength: () => number;
	getPointAtLength: (distance: number) => DOMPoint;
}

interface EventTarget {
	classList: DOMTokenList;
	tagName: string;
	parentElement: HTMLElement | null;
	parentNode: any;
	dataset: DOMStringMap;
	innerText: string;
	innerHTML: string;
	textContent: string;
	value: any;
	checked: boolean;
	style: CSSStyleDeclaration;
	closest: (selector: string) => Element | null;
}

declare let d3: any;
declare let ThreeD: any;
declare let Dropbox: any;
declare let Cloud: any;
declare let ldb: LegacyLdb;
declare let ensureEl: (id: string) => any;
declare let isCtrlClick: (event: Event) => boolean;

declare let INFO: boolean;
declare let VERSION: string;

declare let optionsTrigger: HTMLElement;
declare let regenerate: HTMLElement;
declare let collapsible: HTMLElement;
declare let layersPreset: LegacyControlElement;
declare let removePresetButton: HTMLElement;
declare let savePresetButton: HTMLElement;
declare let mapHistory: Array<{ seed: string; width: number; height: number; template: string; created: number }>;
declare let mapId: number;

declare let customizationMenu: HTMLElement;
declare let toolsContent: HTMLElement;
declare let layersContent: HTMLElement;
declare let styleContent: HTMLElement;
declare let aboutContent: HTMLElement;

declare let stylePreset: LegacyControlElement;
declare let styleToLoad: LegacyControlElement;
declare let styleSaverName: LegacyControlElement;
declare let styleSaverJSON: LegacyControlElement;
declare let styleSaverTip: HTMLElement;
declare let removeStyleButton: HTMLElement;
declare let mapFilters: any;

declare let mapWidthInput: LegacyControlElement;
declare let mapHeightInput: LegacyControlElement;
declare let mapSizeOutput: LegacyControlElement;
declare let latitudeOutput: LegacyControlElement;
declare let longitudeOutput: LegacyControlElement;
declare let precOutput: LegacyControlElement;
declare let temperatureScale: LegacyControlElement;
declare let growthRate: LegacyControlElement;
declare let hideLabels: LegacyCheckboxControl;
declare let rescaleLabels: LegacyCheckboxControl;
declare let hideEmblems: LegacyCheckboxControl;
declare let manorsOutput: LegacyControlElement;
declare let culturesOutput: LegacyControlElement;
declare let pointsOutputFormatted: LegacyControlElement;
declare let optionsSeed: LegacyControlElement;
declare let uiSize: LegacyControlElement;
declare let zoomExtentMin: LegacyControlElement;
declare let zoomExtentMax: LegacyControlElement;
declare let themeColorInput: LegacyControlElement;
declare let themeHueInput: LegacyControlElement;
declare let transparencyInput: LegacyControlElement;
declare let distanceScaleInput: LegacyControlElement;
declare let populationRateInput: LegacyControlElement;
declare let urbanizationInput: LegacyControlElement;
declare let urbanDensityInput: LegacyControlElement;
declare let latitudeInput: LegacyControlElement;
declare let longitudeInput: LegacyControlElement;
declare let mapSizeInput: LegacyControlElement;
declare let precInput: LegacyControlElement;
declare let stateLabelsModeInput: LegacyControlElement;
declare let yearInput: LegacyControlElement;
declare let eraInput: LegacyControlElement;
declare let shapeRendering: LegacyValueControl;
declare let landmass: any;
declare let oceanPattern: any;
declare let fogging: any;
declare let zoom: any;
declare let scaleBar: any;
declare let compass: any;
declare let rulers: any;
declare let styleTab: LegacyControlElement;
declare var heightExponentInput: LegacyControlElement;

declare let cells: any;
declare let biomes: any;
declare let prec: any;
declare let population: any;
declare let cults: any;
declare let relig: any;
declare let borders: any;
declare let regions: any;
declare let icons: any;
declare let texture: any;
declare let ocean: any;
declare let statesBody: any;
declare let statesHalo: any;
declare let stateBorders: any;
declare let provinceBorders: any;
declare let roads: any;
declare let trails: any;
declare let searoutes: any;
declare let ruler: any;
declare let debug: any;
declare let coordinates: any;
declare let gridOverlay: any;

declare var grid: any;
declare let _distanceScale: number;
declare let _populationRate: number;
declare let _urbanization: number;
declare let _urbanDensity: number;
declare let _nameBases: any[];
declare let mapNameInput: LegacyControlElement;

declare let heightmapColorSchemes: Record<string, string[]>;

declare let addCustomColorScheme: (scheme: string) => void;
declare let updateTextureSelectValue: (href: string) => void;
declare let lock: (settingId: string) => void;
declare var drawReliefIcons: () => void;
declare var drawTemperature: () => void;
declare var drawStateLabels: (list?: number[]) => void;
declare let drawPrecipitation: () => void;
declare let drawBiomes: () => void;
declare let drawRivers: () => void;
declare let convertTemperature: (temp: number, scale?: string) => string;
declare let parseTransform: (str: string) => [number, number, number, number, number, number];
declare let getGridPolygon: (cellIndex: number) => [number, number][];
declare var getPackPolygon: (cellIndex: number) => [number, number][];
declare let getIsolines: (...args: any[]) => any;
declare let editStyle: (element: string, group?: string) => void;
declare let cleanupData: () => void;
declare let parseMapVersion: (version: string) => number[];
declare let isValidVersion: (version: string) => boolean;
declare let compareVersions: (a: string, b: string) => number;
declare let generateMapOnLoad: () => Promise<void>;
declare let applyStoredOptions: () => void;
declare let applyStyleOnLoad: () => void;
declare let initiateAutosave: () => void;
declare let regeneratePrompt: (options?: unknown) => void;
declare let saveMap: (method?: string) => Promise<void>;
declare let quickLoad: () => Promise<void>;
declare let toggle3dOptions: () => void;
declare let toggleSaveReminder: () => void;
declare let drawLayers: () => void;
declare let showDataTip: (x: number, y: number) => void;
declare let toggleTexture: (event?: Event) => void;
declare let toggleHeight: (event?: Event) => void;
declare let toggleLakes: (event?: Event) => void;
declare let toggleBiomes: (event?: Event) => void;
declare let toggleCells: (event?: Event) => void;
declare let toggleGrid: (event?: Event) => void;
declare let toggleCoordinates: (event?: Event) => void;
declare let toggleCompass: (event?: Event) => void;
declare let toggleRivers: (event?: Event) => void;
declare let toggleRelief: (event?: Event) => void;
declare let toggleCultures: (event?: Event) => void;
declare let toggleStates: (event?: Event) => void;
declare let toggleProvinces: (event?: Event) => void;
declare let toggleZones: (event?: Event) => void;
declare let toggleBorders: (event?: Event) => void;
declare let toggleReligions: (event?: Event) => void;
declare let toggleRoutes: (event?: Event) => void;
declare let toggleTemperature: (event?: Event) => void;
declare let togglePopulation: (event?: Event) => void;
declare let toggleIce: (event?: Event) => void;
declare let togglePrecipitation: (event?: Event) => void;
declare let toggleEmblems: (event?: Event) => void;
declare let toggleLabels: (event?: Event) => void;
declare let toggleBurgIcons: (event?: Event) => void;
declare let toggleMilitary: (event?: Event) => void;
declare let toggleMarkers: (event?: Event) => void;
declare let toggleRulers: (event?: Event) => void;
declare let toggleScaleBar: (event?: Event) => void;
declare let toggleVignette: (event?: Event) => void;
declare let toggleAddBurg: () => void;
declare let toggleAddLabel: () => void;
declare let toggleAddRiver: () => void;
declare let toggleAddMarker: () => void;
declare let createRoute: (group?: string) => void;
declare let createRiver: () => void;
declare let editRoute: (id: string) => void;
declare let editRiver: (id: string) => void;
declare let editRouteGroups: () => void;
declare var getFileName: (name?: string) => string;
declare var downloadFile: (content: string | Blob, name: string, type?: string) => void;
declare var confirmationDialog: (options: { title?: string; message?: string; cancel?: string; confirm?: string; onCancel?: () => void; onConfirm?: () => void }) => void;
declare let applySorting: (headers: Element) => void;
declare let highlightElement: (element: Element, zoom?: number) => void;
declare let sortLines: (element?: unknown) => void;
declare let clicked: () => void;
declare let getSegmentId: (points: number[][], point: number[], step?: number) => number;
declare let editHeightmap: any;
declare let editBiomes: () => void;
declare let editStates: () => Promise<void>;
declare let editProvinces: () => void;
declare let editDiplomacy: () => void;
declare let editCoastlineSettings: () => void;
declare let editCultures: () => Promise<void>;
declare let editZones: () => void;
declare let editReligions: () => Promise<void>;
declare let openEmblemEditor: () => void;
declare let editNotes: (id?: string, name?: string) => void;
declare let overviewCharts: () => void;
declare let overviewBurgs: (settings?: { stateId?: number | null; cultureId?: number | null }) => void;
declare let overviewRoutes: () => void;
declare let overviewRivers: () => void;
declare let overviewMilitary: () => void;
declare let overviewMarkers: () => void;
declare let viewCellDetails: () => void;
declare let unselect: () => void;
declare let capitalize: (str: string) => string;
declare let si: (value: number) => string;
declare let routeName: LegacyControlElement;
declare let riverName: LegacyControlElement;
declare let regimentsFilter: LegacyControlElement;
declare let regimentsHeader: HTMLElement;
declare let regimentAdd: HTMLElement;
declare let riversHeader: HTMLElement;
declare let riversFooterNumber: HTMLElement;
declare let riversFooterDischarge: HTMLElement;
declare let riversFooterLength: HTMLElement;
declare let riversFooterWidth: HTMLElement;
declare let zonesRemove: HTMLElement;
declare let undo: HTMLElement;
declare let redo: HTMLElement;
declare let elSelected: any;
declare let lineGen: any;
declare let ElevationProfile: {open: AnyFn};
declare let NamesbaseEditor: {open: AnyFn};
declare let applyOption: ($select: any, value: any, name?: any) => void;
declare let minmax: (value: number, min: number, max: number) => number;
declare let fitLegendBox: () => void;
declare let calculateFriendlyGridSize: () => string;
declare let generatePrecipitation: () => void;
declare let toggleAssistant: () => void;
declare let selectStyleElement: () => void;
declare let ra: <T>(arr: T[] | ArrayLike<T>) => T;
declare let rn: (value: number, digits?: number) => number;
declare let round: (inputString?: string, decimals?: number) => string;
declare let getVertexPath: (cellsArray: number[]) => string;
declare var getFeaturePath: (feature: unknown) => string;
declare var getPin: (shape?: string, fill?: string, stroke?: string) => string;
declare var terrain: any;
declare var armies: any;
declare let mapToLoad: any;
declare let tooltip: any;
declare let google: any;
declare let precreatedHeightmaps: any;
declare let statesNumber: any;
declare let provincesRatio: any;
declare let manorsInput: any;
declare let sizeVariety: any;
declare let viewMode: any;
declare let viewStandard: any;
declare let heightmap3DView: any;
declare let options3dUpdate: any;
declare let preview3d: any;
declare let optionsContainer: any;
declare let options3dMesh: any;
declare let options3dGlobe: any;
declare let options3dOBJSave: any;
declare let options3dScaleRange: any;
declare let options3dScaleNumber: any;
declare let options3dLightnessRange: any;
declare let options3dLightnessNumber: any;
declare let options3dSunX: any;
declare let options3dSunY: any;
declare let options3dMeshRotationRange: any;
declare let options3dMeshRotationNumber: any;
declare let options3dMeshSkinResolution: any;
declare let options3dGlobeRotationRange: any;
declare let options3dGlobeRotationNumber: any;
declare let options3dMeshLabels3d: any;
declare let options3dMeshSkyMode: any;
declare let options3dColorSection: any;
declare let options3dMeshSky: any;
declare let options3dMeshWater: any;
declare let options3dGlobeResolution: any;
declare let options3dSunColor: any;
declare let options3dSubdivide: any;
declare let tinymce: any;

declare let Biomes: any;

declare let editUnits: () => void;
declare let openURL: (url: string) => void;
declare let editBurgGroups: () => void;
declare let editBurg: (id?: number | string) => void;
declare let editEmblem: (type: string, id: string, el: unknown) => void;
declare let showBurgTemperatureGraph: (id: number) => void;
declare let highlightEmblemElement: (type: string, element: unknown) => void;
declare let calculateVoronoi: (points: [number, number][], boundary: [number, number][]) => { cells: import("@fmg/types").Cells; vertices: import("@fmg/types").Vertices };
declare let debounce: <T extends AnyFn>(fn: T, wait: number) => T;
declare let MOBILE: boolean;
declare let drawGrid: () => void;
declare let restoreDefaultEvents: () => void;
declare let focusOn: () => void;
declare let findCell: (x: number, y: number, radius?: number) => number | undefined;
declare let findGridCell: (x: number, y: number, grid: import("@fmg/types").Grid) => number;
declare let findAll: (x: number, y: number, radius: number) => number[];
declare let isLand: (cellId: number) => boolean;
declare let aleaPRNG: (seed: string) => () => number;
declare let shouldRegenerateGrid: (grid: unknown, expectedSeed: unknown) => boolean;
declare let generateGrid: () => unknown;
declare let generateSeed: () => string;
declare let last: <T>(arr: T[]) => T;
declare let link: (URL: string, description: string) => string;
declare let getComposedPath: (event: Node | Window | ShadowRoot | Document) => Array<Node | Window>;
declare let drawStates: () => void;
declare var drawBorders: () => void;
declare let mapURL: HTMLInputElement;
declare let loadMapFromURL: (maplink: string, random?: number) => Promise<void>;
declare let uploadMap: (file: Blob | File, callback?: () => void) => void;
declare let fitContent: () => string;
declare let gauss: (expected?: number, deviation?: number, min?: number, max?: number, round?: number) => number;
declare let rw: (object: { [key: string]: number }) => string;
declare let rand: (min?: number, max?: number) => number;
declare let getArea: (rawArea: number) => number;
declare let getAreaUnit: (squareMark?: string) => string;
declare let getPrecipitation: (precipitation: number) => string;
declare let isWater: (cellId: number) => boolean;
declare let rollups: (values: any[], reduce: (values: any[]) => any, ...keys: ((value: any, index: number, array: any[]) => unknown)[]) => any;
declare let removeCircle: () => void;
declare let recalculatePopulation: () => void;
declare let getRandomColor: () => string;
declare let drawHeights: (options: unknown) => string;
declare let listen: (element: { on: (...args: unknown[]) => void; off: (...args: unknown[]) => void }, event: string, handler: (...args: unknown[]) => void) => () => void;
declare let selectIcon: (initial: string, callback: (value: string) => void) => void;
declare let unique: (arr: any[]) => any[];
declare let drawProvinces: () => void;
declare let drawReligions: () => void;
declare let drawCultures: () => void;
declare let getTemperatureLikeness: (cellId: number) => number;
declare let overviewRegiments: (state?: number) => void;
declare let configMarkersGeneration: () => void;
declare let editMarker: (markerI?: number) => void;
declare let addMarker: HTMLElement;
declare let wiki: (term: string) => void;
declare let sanitizeId: (str: string) => string;
declare let removeLegend: () => void;
declare let generateWithAi: (prompt?: string, onApply?: (result: string) => void) => void;
declare let P: (probability: number) => boolean;
declare let resetZoom: (duration?: number) => void;
declare let Rulers: {new (): any};

declare let burgBody: HTMLElement;
declare let burgName: LegacyControlElement;
declare let burgPopulation: LegacyControlElement;
declare let burgsHeader: HTMLElement;
declare let burgsFooterBurgs: HTMLElement;
declare let burgsFooterPopulation: HTMLElement;
declare let burgsOverviewRefresh: HTMLElement;
declare let addBurgTool: HTMLElement;
declare let addNewBurg: HTMLElement;
declare let burgsInfo: HTMLElement;
declare let burgsListToLoad: LegacyControlElement;
declare let markersOverviewRefresh: HTMLElement;
declare let markerTypeSelectMenu: HTMLElement;
declare let markersFooterTotal: HTMLElement;
declare let markersHeader: HTMLElement;
declare let markerAdd: HTMLElement;

declare let routesHeader: HTMLElement;
declare let routesFooterNumber: any;
declare let routesFooterLength: any;

declare let unitsBottom: HTMLElement;
declare let addOpisometer: HTMLElement;
declare let addRouteOpisometer: HTMLElement;
declare let addPlanimeter: HTMLElement;

declare let biomesHeader: HTMLElement;
declare let biomesFooter: any;
declare let biomesFooterBiomes: any;
declare let biomesFooterCells: any;
declare let biomesFooterArea: any;
declare let biomesFooterPopulation: any;
declare let biomesBrush: LegacyControlElement;

declare let coastlineArea: HTMLElement;
declare let coastlineGroupName: LegacyControlElement;
declare let coastlineGroup: LegacyControlElement;

declare let emblemImageToLoad: LegacyControlElement;
declare let emblemSVGToLoad: LegacyControlElement;
declare let emblemsDownloadSize: LegacyControlElement;
declare let COA: any;

declare let labelGroupInput: LegacyControlElement;
declare let labelGroupSelect: LegacyControlElement;
declare let legendsToLoad: LegacyControlElement;

declare let militaryHeader: HTMLElement;
declare let militaryFooterStates: any;
declare let militaryFooterForcesTotal: any;
declare let militaryFooterForces: any;
declare let militaryFooterRate: any;
declare let militaryFooterAlert: any;
declare let militaryOptionsTable: HTMLTableElement;
declare let militaryOverviewRefresh: HTMLElement;
declare let regimentsOverviewRefresh: HTMLElement;
declare let regimentComposition: HTMLElement;
declare let Military: any;
declare let Battle: any;

declare let lakeName: LegacyControlElement;
declare let lakeGroup: LegacyControlElement;
declare let lakeGroupName: LegacyControlElement;
declare let Lakes: any;

declare let reliefIconsDiv: HTMLElement;
declare let reliefTools: HTMLElement;
declare let reliefBulkAdd: HTMLElement;
declare let reliefBulkRemove: HTMLElement;
declare let reliefEditorSet: LegacyControlElement;
declare let reliefSize: LegacyControlElement;
declare let reliefSizeNumber: LegacyControlElement;
declare let reliefIndividual: HTMLElement;
declare let reliefSizeDiv: HTMLElement;
declare let reliefRadiusDiv: HTMLElement;
declare let reliefSpacingDiv: HTMLElement;
declare let reliefIconsSeletionAny: HTMLElement;
declare let reliefRadiusNumber: LegacyControlElement;
declare let reliefSpacingNumber: LegacyControlElement;
declare let error: string;
declare let findAllInQuadtree: (x: number, y: number, radius: number, tree?: unknown) => [number, number, SVGElement][];

declare let zonesFilterType: LegacyControlElement;
declare let zonesFooterNumber: any;
declare let zonesBrush: LegacyControlElement;

declare let drawCoordinates: () => void;

declare let getMapURL: (type: string, options?: Record<string, unknown>) => Promise<string>;
declare let cellsDensityMap: () => void;
declare let getCellsDensityColor: (cellId: number) => string;
declare let changeCellsDensity: (value: number) => void;
declare let applyGraphSize: () => void;
declare let undraw: () => void;

declare let cellInfo: HTMLElement;
declare let notesEditor: HTMLElement;
declare let markerEditor: HTMLElement;
declare let riversOverview: HTMLElement;
declare let burgsOverview: HTMLElement;
declare let biomesEditor: HTMLElement;
declare let diplomacyHeader: HTMLElement;
declare let diplomacyMatrix: HTMLElement;
declare let religionsEditor: HTMLElement;
declare let statesEditor: HTMLElement;
declare let diplomacyEditor: HTMLElement;
declare let militaryOverview: HTMLElement;
declare let provincesEditor: HTMLElement;
declare let culturesEditor: HTMLElement;

declare let infoX: HTMLElement;
declare let infoY: HTMLElement;
declare let infoLat: HTMLElement;
declare let infoLon: HTMLElement;
declare let infoGeozone: HTMLElement;
declare let infoCell: HTMLElement;
declare let infoArea: HTMLElement;
declare let infoElevation: HTMLElement;
declare let infoDepth: HTMLElement;
declare let infoTemp: HTMLElement;
declare let infoPrec: HTMLElement;
declare let infoRiver: HTMLElement;
declare let infoState: HTMLElement;
declare let infoProvince: HTMLElement;
declare let infoCulture: HTMLElement;
declare let infoReligion: HTMLElement;
declare let infoPopulation: HTMLElement;
declare let infoBurg: HTMLElement;
declare let infoFeature: HTMLElement;
declare let infoBiome: HTMLElement;

declare let getAdjective: (name: string) => string;

declare function prompt(message: string, options?: any, callback?: (value: string) => void): void;

  // Cultures / Religions editor globals
  declare let applySortingByHeader: (headerContainer: string) => void;
	declare var openPicker: (fill: string, callback: (newFill: string) => void) => void;
  declare let abbreviate: (name: string, restricted?: string[]) => string;
  declare var drawPopulation: () => void;
  declare var legend: any;
  declare var ruralPop: HTMLInputElement;
  declare var urbanPop: HTMLInputElement;
  declare var totalPop: HTMLElement;
  declare var totalPopPerc: HTMLElement;
  declare let l: (n: number) => string;
  declare let culturesAutoChange: HTMLInputElement;
  declare let culturesFooter: HTMLElement;
  declare let culturesBrush: any;
  declare let culturesAdd: HTMLElement;
  declare let religionsHeader: HTMLElement;

  // Heightmap editor globals
  declare let THREE: any;
  declare let edits: any;
  declare let cellTypeFilter: any;
  declare let mapLayers: HTMLElement;
  declare let heightmapEditMode: any;
  declare let changeViewMode: (mode: string) => void;
	declare let applyTemplate: any;
	declare let convertImage: any;
	declare let allowErosionBox: any;
	declare let exitCustomization: any;
	declare let turnButtonOn: (buttonId: string) => void;
	declare let heightmapInfoX: any;
	declare let heightmapInfoY: any;
	declare let heightmapInfoCell: any;
	declare let heightmapInfoHeight: any;
  declare let heightmapBrushRadius: any;
  declare let templateRedo: HTMLElement;
  declare let templateUndo: HTMLElement;
  declare let drawRoutes: () => void;

	// Additional missing globals
	declare let adjustLabels: any;
	declare let allowErosion: any;
	declare let battleAttackers: any;
	declare let battleDefenders: any;
	declare let biomesEditorRefresh: any;
	declare let burgs: any[];
	declare let colorsAssigned: any;
	declare let colorsAssignedContainer: HTMLElement;
	declare let colorsSelect: HTMLSelectElement;
	declare let colorsSelectFriendly: any;
	declare let colorsSelectValue: any;
	declare let colorsUnassigned: any;
	declare let colorsUnassignedContainer: HTMLElement;
	declare let conditionSign: HTMLElement;
	declare let convertColors: any;
	declare let convertOverlay: any;
	declare let convertOverlayNumber: HTMLInputElement;
	declare let createTypedArray: (options: { maxValue: number; length: number; from?: ArrayLike<number> }) => Uint8Array | Uint16Array | Uint32Array;
	declare let culturesEditorRefresh: any;
	declare let customPresetPrefix: string;
	declare let diplomacyEditorRefresh: any;
	declare let drawTexture: () => void;
	declare let editCoastline: () => void;
	declare let editIce: (element: EventTarget | null) => void;
	declare let editLabel: () => void;
	declare let editLake: () => void;
	declare let editRegiment: (selector?: string) => void;
	declare let editReliefIcon: () => void;
	declare let enterStandardView: () => void;
	declare let findGridAll: (x: number, y: number, radius: number) => number[];
	declare let getCurrentPreset: () => string;
	declare let getMixedColor: (colorToMix: string, mix?: number, bright?: number) => string;
	declare let heightmapBrushPower: any;
	declare let imageConverter: any;
	declare let imageConverterPalette: any;
	declare let imageToLoad: any;
	declare let lim: (value: number) => number;
	declare let list: any;
	declare let loopSubdivision: any;
	declare let onMouseMove: (event: MouseEvent) => void;
	declare let pickerH: LegacyControlElement;
	declare let pickerHEX: LegacyControlElement;
	declare let pickerHSL_H: LegacyControlElement;
	declare let pickerHSL_L: LegacyControlElement;
	declare let pickerHSL_S: LegacyControlElement;
	declare let pickerL: LegacyControlElement;
	declare let pickerRGB_B: LegacyControlElement;
	declare let pickerRGB_G: LegacyControlElement;
	declare let pickerRGB_R: LegacyControlElement;
	declare let pickerS: LegacyControlElement;
	declare let Pint: any;
		declare let polylabel: (polygon: number[][][], precision?: number) => [number, number];
	declare let provinceInfo: HTMLElement;
	declare let provinceNameEditor: HTMLElement;
	declare let provinceNameEditorCustomForm: any;
	declare let provinceNameEditorSelectForm: any;
	declare let provincesAdd: HTMLElement;
	declare let provincesBrush: any;
	declare let provincesEditorRefresh: any;
	declare let provincesFooter: HTMLElement;
	declare let provincesFooterArea: HTMLElement;
	declare let provincesFooterPopulation: HTMLElement;
	declare let provincesHeader: HTMLElement;
	declare let provincesTreeType: any;
	declare let rankCells: () => void;
	declare let regenerateEmblems: () => void;
	declare let regimentSelectorHeader: HTMLElement;
	declare let religionsAdd: HTMLElement;
	declare let religionsAutoChange: HTMLInputElement;
	declare let religionsEditorRefresh: any;
	declare let religionsFooter: HTMLElement;
	declare let renderOcean: any;
	declare let rescaleHigher: HTMLElement;
	declare let rescaleLower: HTMLElement;
	declare let rescaleModifier: any;
	declare let RgbQuant: any;
	declare let shiftCompass: () => void;
	declare let stateNameEditor: HTMLElement;
	declare let stateNameEditorCustomForm: any;
	declare let stateNameEditorSelectForm: any;
	declare let stateNameEditorFullRegenerate: any;
	declare let stateNameEditorUpdateLabel: any;
	declare let statesAdd: HTMLElement;
	declare let statesAutoChange: HTMLInputElement;
	declare let statesBrush: any;
	declare let statesEditorRefresh: any;
	declare let statesFooter: HTMLElement;
	declare let statesHeader: HTMLElement;
	declare let statesInfo: HTMLElement;
	declare let statesTreeType: any;
	declare let styleLegendBack: any;
	declare let styleLegendColItems: any;
	declare let styleLegendOpacity: any;
	declare let templateBody: HTMLElement;
	declare let templateToLoad: any;
	declare let throttle: <T extends AnyFn>(fn: T, wait: number) => T;
	declare let turnButtonOff: (buttonId: string) => void;
	declare let zonesEditorRefresh: any;
		declare let color: AnyFn;
}

export {};
