// Override d3 BaseType to any so legacy d3 callbacks don't require explicit this typing
// Augment d3 Selection to allow any-typed 'this' in callbacks for legacy code
declare module "d3-selection" {
	interface Selection<GElement, Datum, PElement, PDatum> {
		each(func: (this: any, d: Datum, i: number, groups: GElement[] | ArrayLike<GElement>) => void): this;
		filter(value: (this: any, d: Datum, i: number, groups: GElement[] | ArrayLike<GElement>) => boolean): Selection<GElement, Datum, PElement, PDatum>;
	}
}

type AnyFn = (...args: any[]) => any;
type LegacyCheckboxControl = {checked: boolean};
type LegacyValueControl = {value: string};
type LegacyControlElement = HTMLElement & {
	value: any;
	min: any;
	max: any;
	step: any;
	checked: any;
	files: any;
	options: HTMLOptionsCollection | any;
	selectedOptions: HTMLCollectionOf<HTMLOptionElement> | any;
	add: (item: HTMLOptionElement, before?: HTMLOptionElement | number | null) => void;
	disabled: boolean;
	click: () => void;
	width: any;
	height: any;
	getScreenCTM: () => DOMMatrix | null;
	dataset: DOMStringMap;
	style: CSSStyleDeclaration;
};
type LegacyOptions = Record<string, any>;
type LegacyLdb = {
	get: (key: string) => Promise<Blob | null>;
	set: (key: string, value: Blob | string) => Promise<unknown> | void;
};

declare global {
interface Window {
	Cloud: any;
	Dropbox: any;
	fonts: Array<{family: string; src?: string; unicodeRange?: string; variant?: string}>;
	declareFont: (font: {family: string; src?: string; unicodeRange?: string; variant?: string}) => void;
	tinymce: any;
	edits: any;
	chrome: any;
	ThreeD: any;
	THREE: any;
	loopSubdivision: any;
	drawFeatures: () => void;
	getFileName: (name?: string) => string;
	downloadFile: (content: string | Blob, name: string, type?: string) => void;
	fog: (id: string, path: string) => void;
	unfog: (id?: string) => void;
	locked: (settingId: string) => boolean;
}

interface Element {
	value: any;
	checked: any;
	options: any;
	files: any;
	disabled: any;
	innerHTML: any;
	textContent: any;
	type: any;
	dataset: DOMStringMap;
	style: CSSStyleDeclaration;
	points: any;
	getTotalLength: () => number;
	getPointAtLength: (distance: number) => DOMPoint;
}

interface EventTarget {
	classList: DOMTokenList;
	tagName: string;
	parentElement: HTMLElement | null;
	parentNode: any;
	dataset: DOMStringMap;
	innerText: string;
	innerHTML: string;
	textContent: string;
	value: any;
	checked: boolean;
	style: CSSStyleDeclaration;
	closest: (selector: string) => Element | null;
}

declare let d3: any;
declare let ThreeD: any;
declare let Dropbox: any;
declare let Cloud: any;
declare let ldb: LegacyLdb;
declare let ensureEl: (id: string) => any;
declare let isCtrlClick: (event: Event) => boolean;

declare let INFO: boolean;
declare let VERSION: string;

declare let optionsTrigger: HTMLElement;
declare let regenerate: HTMLElement;
declare let collapsible: HTMLElement;
declare let layersPreset: LegacyControlElement;
declare let removePresetButton: HTMLElement;
declare let savePresetButton: HTMLElement;
declare let mapHistory: Array<{ seed: string; width: number; height: number; template: string; created: number }>;
declare let mapId: number;

declare let customizationMenu: HTMLElement;
declare let toolsContent: HTMLElement;
declare let layersContent: HTMLElement;
declare let styleContent: HTMLElement;
declare let aboutContent: HTMLElement;

declare let stylePreset: LegacyControlElement;
declare let styleToLoad: LegacyControlElement;
declare let styleSaverName: LegacyControlElement;
declare let styleSaverJSON: LegacyControlElement;
declare let styleSaverTip: HTMLElement;
declare let removeStyleButton: HTMLElement;
declare let mapFilters: any;

declare let mapWidthInput: LegacyControlElement;
declare let mapHeightInput: LegacyControlElement;
declare let mapSizeOutput: LegacyControlElement;
declare let latitudeOutput: LegacyControlElement;
declare let longitudeOutput: LegacyControlElement;
declare let precOutput: LegacyControlElement;
declare let temperatureScale: LegacyControlElement;
declare let growthRate: LegacyControlElement;
declare let hideLabels: LegacyCheckboxControl;
declare let rescaleLabels: LegacyCheckboxControl;
declare let hideEmblems: LegacyCheckboxControl;
declare let manorsOutput: LegacyControlElement;
declare let culturesOutput: LegacyControlElement;
declare let pointsOutputFormatted: LegacyControlElement;
declare let optionsSeed: LegacyControlElement;
declare let uiSize: LegacyControlElement;
declare let zoomExtentMin: LegacyControlElement;
declare let zoomExtentMax: LegacyControlElement;
declare let themeColorInput: LegacyControlElement;
declare let themeHueInput: LegacyControlElement;
declare let transparencyInput: LegacyControlElement;
declare let distanceScaleInput: LegacyControlElement;
declare let populationRateInput: LegacyControlElement;
declare let urbanizationInput: LegacyControlElement;
declare let urbanDensityInput: LegacyControlElement;
declare let latitudeInput: LegacyControlElement;
declare let longitudeInput: LegacyControlElement;
declare let mapSizeInput: LegacyControlElement;
declare let precInput: LegacyControlElement;
declare let stateLabelsModeInput: LegacyControlElement;
declare let yearInput: LegacyControlElement;
declare let eraInput: LegacyControlElement;
declare let shapeRendering: LegacyValueControl;
declare let landmass: any;
declare let oceanPattern: any;
declare let fogging: any;
declare let zoom: any;
declare let scaleBar: any;
declare let compass: any;
declare let rulers: any;
declare let styleTab: LegacyControlElement;
declare var heightExponentInput: LegacyControlElement;

declare let cells: any;
declare let biomes: any;
declare let prec: any;
declare let population: any;
declare let cults: any;
declare let relig: any;
declare let borders: any;
declare let regions: any;
declare let icons: any;
declare let texture: any;
declare let ocean: any;
declare let statesBody: any;
declare let statesHalo: any;
declare let stateBorders: any;
declare let provinceBorders: any;
declare let roads: any;
declare let trails: any;
declare let searoutes: any;
declare let ruler: any;
declare let debug: any;
declare let coordinates: any;
declare let gridOverlay: any;

declare var grid: any;
declare let _distanceScale: number;
declare let _populationRate: number;
declare let _urbanization: number;
declare let _urbanDensity: number;
declare let _nameBases: any[];
declare let mapNameInput: LegacyControlElement;

declare let heightmapColorSchemes: Record<string, string[]>;

declare let addCustomColorScheme: (scheme: string) => void;
declare let updateTextureSelectValue: (href: string) => void;
declare let lock: AnyFn;
declare var drawReliefIcons: AnyFn;
declare var drawTemperature: AnyFn;
declare var drawStateLabels: AnyFn;
declare let drawPrecipitation: AnyFn;
declare let drawBiomes: AnyFn;
declare let drawRivers: AnyFn;
declare let convertTemperature: AnyFn;
declare let parseTransform: AnyFn;
declare let getGridPolygon: AnyFn;
declare var getPackPolygon: AnyFn;
declare let getIsolines: AnyFn;
declare let editStyle: AnyFn;
declare let cleanupData: AnyFn;
declare let parseMapVersion: AnyFn;
declare let isValidVersion: AnyFn;
declare let compareVersions: AnyFn;
declare let generateMapOnLoad: AnyFn;
declare let applyStoredOptions: AnyFn;
declare let applyStyleOnLoad: AnyFn;
declare let initiateAutosave: AnyFn;
declare let regeneratePrompt: AnyFn;
declare let saveMap: AnyFn;
declare let quickLoad: AnyFn;
declare let toggle3dOptions: AnyFn;
declare let toggleSaveReminder: AnyFn;
declare let drawLayers: AnyFn;
declare let showDataTip: AnyFn;
declare let toggleTexture: AnyFn;
declare let toggleHeight: AnyFn;
declare let toggleLakes: AnyFn;
declare let toggleBiomes: AnyFn;
declare let toggleCells: AnyFn;
declare let toggleGrid: AnyFn;
declare let toggleCoordinates: AnyFn;
declare let toggleCompass: AnyFn;
declare let toggleRivers: AnyFn;
declare let toggleRelief: AnyFn;
declare let toggleCultures: AnyFn;
declare let toggleStates: AnyFn;
declare let toggleProvinces: AnyFn;
declare let toggleZones: AnyFn;
declare let toggleBorders: AnyFn;
declare let toggleReligions: AnyFn;
declare let toggleRoutes: AnyFn;
declare let toggleTemperature: AnyFn;
declare let togglePopulation: AnyFn;
declare let toggleIce: AnyFn;
declare let togglePrecipitation: AnyFn;
declare let toggleEmblems: AnyFn;
declare let toggleLabels: AnyFn;
declare let toggleBurgIcons: AnyFn;
declare let toggleMilitary: AnyFn;
declare let toggleMarkers: AnyFn;
declare let toggleRulers: AnyFn;
declare let toggleScaleBar: AnyFn;
declare let toggleVignette: AnyFn;
declare let toggleAddBurg: AnyFn;
declare let toggleAddLabel: AnyFn;
declare let toggleAddRiver: AnyFn;
declare let toggleAddMarker: AnyFn;
declare let createRoute: AnyFn;
declare let createRiver: AnyFn;
declare let editRoute: AnyFn;
declare let editRiver: AnyFn;
declare let editRouteGroups: AnyFn;
declare var closeDialogs: AnyFn;
declare var tip: any;
declare var getFileName: (name?: string) => string;
declare var downloadFile: (content: string | Blob, name: string, type?: string) => void;
declare var confirmationDialog: AnyFn;
declare let applySorting: AnyFn;
declare let highlightElement: AnyFn;
declare let sortLines: AnyFn;
declare let clicked: AnyFn;
declare let getSegmentId: AnyFn;
declare let editHeightmap: any;
declare let editBiomes: AnyFn;
declare let editStates: AnyFn;
declare let editProvinces: AnyFn;
declare let editDiplomacy: AnyFn;
declare let editCoastlineSettings: AnyFn;
declare let editCultures: AnyFn;
declare let editZones: AnyFn;
declare let editReligions: AnyFn;
declare let openEmblemEditor: AnyFn;
declare let editNotes: AnyFn;
declare let overviewCharts: AnyFn;
declare let overviewBurgs: AnyFn;
declare let overviewRoutes: AnyFn;
declare let overviewRivers: AnyFn;
declare let overviewMilitary: AnyFn;
declare let overviewMarkers: AnyFn;
declare let viewCellDetails: AnyFn;
declare let unselect: AnyFn;
declare let capitalize: AnyFn;
declare let si: AnyFn;
declare let routeName: LegacyControlElement;
declare let riverName: LegacyControlElement;
declare let regimentsFilter: LegacyControlElement;
declare let regimentsHeader: HTMLElement;
declare let regimentAdd: HTMLElement;
declare let riversHeader: HTMLElement;
declare let riversFooterNumber: HTMLElement;
declare let riversFooterDischarge: HTMLElement;
declare let riversFooterLength: HTMLElement;
declare let riversFooterWidth: HTMLElement;
declare let zonesRemove: HTMLElement;
declare let undo: HTMLElement;
declare let redo: HTMLElement;
declare let elSelected: any;
declare let lineGen: any;
declare let ElevationProfile: {open: AnyFn};
declare let NamesbaseEditor: {open: AnyFn};
declare let applyOption: AnyFn;
declare let minmax: AnyFn;
declare let fitLegendBox: AnyFn;
declare let calculateFriendlyGridSize: AnyFn;
declare let generatePrecipitation: AnyFn;
declare let toggleAssistant: AnyFn;
declare let selectStyleElement: AnyFn;
declare let ra: (array: ArrayLike<any>) => string;
declare let rn: (value: number, digits?: number) => number;
declare let round: (value: string) => string;
declare let getVertexPath: AnyFn;
declare var getFeaturePath: AnyFn;
declare var getPin: AnyFn;
declare var terrain: any;
declare var armies: any;
declare var fonts: Array<{family: string; src?: string; unicodeRange?: string; variant?: string}>;
declare let mapToLoad: any;
declare let tooltip: any;
declare let google: any;
declare let precreatedHeightmaps: any;
declare let statesNumber: any;
declare let provincesRatio: any;
declare let manorsInput: any;
declare let sizeVariety: any;
declare let viewMode: any;
declare let viewStandard: any;
declare let heightmap3DView: any;
declare let options3dUpdate: any;
declare let preview3d: any;
declare let optionsContainer: any;
declare let options3dMesh: any;
declare let options3dGlobe: any;
declare let options3dOBJSave: any;
declare let options3dScaleRange: any;
declare let options3dScaleNumber: any;
declare let options3dLightnessRange: any;
declare let options3dLightnessNumber: any;
declare let options3dSunX: any;
declare let options3dSunY: any;
declare let options3dMeshRotationRange: any;
declare let options3dMeshRotationNumber: any;
declare let options3dMeshSkinResolution: any;
declare let options3dGlobeRotationRange: any;
declare let options3dGlobeRotationNumber: any;
declare let options3dMeshLabels3d: any;
declare let options3dMeshSkyMode: any;
declare let options3dColorSection: any;
declare let options3dMeshSky: any;
declare let options3dMeshWater: any;
declare let options3dGlobeResolution: any;
declare let options3dSunColor: any;
declare let options3dSubdivide: any;
declare let tinymce: any;

declare let Biomes: any;

declare let editUnits: AnyFn;
declare let openURL: AnyFn;
declare let editBurgGroups: AnyFn;
declare let editBurg: AnyFn;
declare let editEmblem: AnyFn;
declare let showBurgTemperatureGraph: AnyFn;
declare let highlightEmblemElement: AnyFn;
declare let calculateVoronoi: AnyFn;
declare let debounce: <T extends AnyFn>(fn: T, wait: number) => T;
declare let MOBILE: boolean;
declare let drawGrid: AnyFn;
declare let restoreDefaultEvents: AnyFn;
declare let focusOn: AnyFn;
declare let fitMapToScreen: AnyFn;
declare var layerIsOn: AnyFn;
declare let clearMainTip: AnyFn;
declare let parseError: AnyFn;
declare let regenerateMap: AnyFn;
declare let findCell: AnyFn;
declare let findGridCell: AnyFn;
declare let findAll: AnyFn;
declare let isLand: AnyFn;
declare var declareFont: (font: {family: string; src?: string; unicodeRange?: string; variant?: string}) => void;
declare let aleaPRNG: AnyFn;
declare let shouldRegenerateGrid: AnyFn;
declare let generateGrid: AnyFn;
declare let generateSeed: AnyFn;
declare let last: AnyFn;
declare let link: AnyFn;
declare let getComposedPath: AnyFn;
declare let drawStates: AnyFn;
declare var drawBorders: AnyFn;
declare let mapURL: any;
declare let loadMapFromURL: AnyFn;
declare let uploadMap: AnyFn;
declare let fitContent: AnyFn;
declare let gauss: AnyFn;
declare let rw: AnyFn;
declare let rand: AnyFn;
declare let getArea: AnyFn;
declare let getAreaUnit: AnyFn;
declare let getPrecipitation: AnyFn;
declare let isWater: AnyFn;
declare let rollups: AnyFn;
declare let moveCircle: AnyFn;
declare let removeCircle: AnyFn;
declare let recalculatePopulation: AnyFn;
declare let getRandomColor: AnyFn;
declare let drawHeights: AnyFn;
declare let showMainTip: AnyFn;
declare let listen: AnyFn;
declare let selectIcon: AnyFn;
declare let unique: AnyFn;
declare let drawProvinces: AnyFn;
declare let drawReligions: AnyFn;
declare let drawCultures: AnyFn;
declare let getTemperatureLikeness: AnyFn;
declare let overviewRegiments: AnyFn;
declare let configMarkersGeneration: AnyFn;
declare let editMarker: AnyFn;
declare let addMarker: HTMLElement;
declare let wiki: AnyFn;
declare let sanitizeId: AnyFn;
declare let removeLegend: AnyFn;
declare let generateWithAi: AnyFn;
declare let P: AnyFn;
declare let resetZoom: AnyFn;
declare let Rulers: {new (): any};

declare let burgBody: HTMLElement;
declare let burgName: LegacyControlElement;
declare let burgPopulation: LegacyControlElement;
declare let burgsHeader: HTMLElement;
declare let burgsFooterBurgs: HTMLElement;
declare let burgsFooterPopulation: HTMLElement;
declare let burgsOverviewRefresh: HTMLElement;
declare let addBurgTool: HTMLElement;
declare let addNewBurg: HTMLElement;
declare let burgsInfo: HTMLElement;
declare let burgsListToLoad: LegacyControlElement;
declare let markersOverviewRefresh: HTMLElement;
declare let markerTypeSelectMenu: HTMLElement;
declare let markersFooterTotal: HTMLElement;
declare let markersHeader: HTMLElement;
declare let markerAdd: HTMLElement;

declare let routesHeader: HTMLElement;
declare let routesFooterNumber: any;
declare let routesFooterLength: any;

declare let unitsBottom: HTMLElement;
declare let addOpisometer: HTMLElement;
declare let addRouteOpisometer: HTMLElement;
declare let addPlanimeter: HTMLElement;

declare let biomesHeader: HTMLElement;
declare let biomesFooter: any;
declare let biomesFooterBiomes: any;
declare let biomesFooterCells: any;
declare let biomesFooterArea: any;
declare let biomesFooterPopulation: any;
declare let biomesBrush: LegacyControlElement;

declare let coastlineArea: HTMLElement;
declare let coastlineGroupName: LegacyControlElement;
declare let coastlineGroup: LegacyControlElement;

declare let emblemImageToLoad: LegacyControlElement;
declare let emblemSVGToLoad: LegacyControlElement;
declare let emblemsDownloadSize: LegacyControlElement;
declare let COA: any;

declare let labelGroupInput: LegacyControlElement;
declare let labelGroupSelect: LegacyControlElement;
declare let legendsToLoad: LegacyControlElement;

declare let militaryHeader: HTMLElement;
declare let militaryFooterStates: any;
declare let militaryFooterForcesTotal: any;
declare let militaryFooterForces: any;
declare let militaryFooterRate: any;
declare let militaryFooterAlert: any;
declare let militaryOptionsTable: HTMLTableElement;
declare let militaryOverviewRefresh: HTMLElement;
declare let regimentsOverviewRefresh: HTMLElement;
declare let regimentComposition: HTMLElement;
declare let Military: any;
declare let Battle: any;

declare let lakeName: LegacyControlElement;
declare let lakeGroup: LegacyControlElement;
declare let lakeGroupName: LegacyControlElement;
declare let Lakes: any;

declare let reliefIconsDiv: HTMLElement;
declare let reliefTools: HTMLElement;
declare let reliefBulkAdd: HTMLElement;
declare let reliefBulkRemove: HTMLElement;
declare let reliefEditorSet: LegacyControlElement;
declare let reliefSize: LegacyControlElement;
declare let reliefSizeNumber: LegacyControlElement;
declare let reliefIndividual: HTMLElement;
declare let reliefSizeDiv: HTMLElement;
declare let reliefRadiusDiv: HTMLElement;
declare let reliefSpacingDiv: HTMLElement;
declare let reliefIconsSeletionAny: HTMLElement;
declare let reliefRadiusNumber: LegacyControlElement;
declare let reliefSpacingNumber: LegacyControlElement;
declare let error: string;
declare let findAllInQuadtree: AnyFn;

declare let zonesFilterType: LegacyControlElement;
declare let zonesFooterNumber: any;
declare let zonesBrush: LegacyControlElement;

declare let drawCoordinates: AnyFn;

declare let getMapURL: AnyFn;
declare let cellsDensityMap: AnyFn;
declare let getCellsDensityColor: AnyFn;
declare let changeCellsDensity: AnyFn;
declare let applyGraphSize: AnyFn;
declare let undraw: AnyFn;

declare let cellInfo: HTMLElement;
declare let notesEditor: HTMLElement;
declare let markerEditor: HTMLElement;
declare let riversOverview: HTMLElement;
declare let burgsOverview: HTMLElement;
declare let biomesEditor: HTMLElement;
declare let diplomacyHeader: HTMLElement;
declare let diplomacyMatrix: HTMLElement;
declare let religionsEditor: HTMLElement;
declare let statesEditor: HTMLElement;
declare let diplomacyEditor: HTMLElement;
declare let militaryOverview: HTMLElement;
declare let provincesEditor: HTMLElement;
declare let culturesEditor: HTMLElement;

declare let infoX: HTMLElement;
declare let infoY: HTMLElement;
declare let infoLat: HTMLElement;
declare let infoLon: HTMLElement;
declare let infoGeozone: HTMLElement;
declare let infoCell: HTMLElement;
declare let infoArea: HTMLElement;
declare let infoElevation: HTMLElement;
declare let infoDepth: HTMLElement;
declare let infoTemp: HTMLElement;
declare let infoPrec: HTMLElement;
declare let infoRiver: HTMLElement;
declare let infoState: HTMLElement;
declare let infoProvince: HTMLElement;
declare let infoCulture: HTMLElement;
declare let infoReligion: HTMLElement;
declare let infoPopulation: HTMLElement;
declare let infoBurg: HTMLElement;
declare let infoFeature: HTMLElement;
declare let infoBiome: HTMLElement;

declare let getAdjective: AnyFn;

declare function prompt(message: string, options?: any, callback?: (value: string) => void): void;

  // Cultures / Religions editor globals
  declare let applySortingByHeader: AnyFn;
	declare var openPicker: any;
  declare let abbreviate: AnyFn;
  declare var drawPopulation: AnyFn;
  declare var legend: any;
  declare var clearLegend: AnyFn;
  declare var drawLegend: AnyFn;
  declare var ruralPop: HTMLInputElement;
  declare var urbanPop: HTMLInputElement;
  declare var totalPop: HTMLElement;
  declare var totalPopPerc: HTMLElement;
  declare let l: (n: number) => string;
  declare let culturesAutoChange: HTMLInputElement;
  declare let culturesFooter: HTMLElement;
  declare let culturesBrush: any;
  declare let culturesAdd: HTMLElement;
  declare let religionsHeader: HTMLElement;

  // Heightmap editor globals
  declare let THREE: any;
  declare let edits: any;
  declare let cellTypeFilter: any;
  declare let mapLayers: HTMLElement;
  declare let heightmapEditMode: any;
  declare let changeViewMode: AnyFn;
	declare let applyTemplate: any;
	declare let convertImage: any;
	declare let allowErosionBox: any;
	declare let exitCustomization: any;
	declare let turnButtonOn: AnyFn;
	declare let heightmapInfoX: any;
	declare let heightmapInfoY: any;
	declare let heightmapInfoCell: any;
	declare let heightmapInfoHeight: any;
  declare let heightmapBrushRadius: any;
  declare let templateRedo: HTMLElement;
  declare let templateUndo: HTMLElement;
  declare let drawRoutes: AnyFn;

	// Additional missing globals
	declare let adjustLabels: any;
	declare let allowErosion: any;
	declare let battleAttackers: any;
	declare let battleDefenders: any;
	declare let biomesEditorRefresh: any;
	declare let burgs: any[];
	declare let colorsAssigned: any;
	declare let colorsAssignedContainer: HTMLElement;
	declare let colorsSelect: HTMLSelectElement;
	declare let colorsSelectFriendly: any;
	declare let colorsSelectValue: any;
	declare let colorsUnassigned: any;
	declare let colorsUnassignedContainer: HTMLElement;
	declare let conditionSign: HTMLElement;
	declare let convertColors: any;
	declare let convertOverlay: any;
	declare let convertOverlayNumber: HTMLInputElement;
	declare let createTypedArray: AnyFn;
	declare let culturesEditorRefresh: any;
	declare let customPresetPrefix: string;
	declare let diplomacyEditorRefresh: any;
	declare let drawTexture: AnyFn;
	declare let editCoastline: AnyFn;
	declare let editIce: AnyFn;
	declare let editLabel: AnyFn;
	declare let editLake: AnyFn;
	declare let editRegiment: AnyFn;
	declare let editReliefIcon: AnyFn;
	declare let enterStandardView: AnyFn;
	declare let findGridAll: AnyFn;
	declare let getCurrentPreset: AnyFn;
	declare let getMixedColor: AnyFn;
	declare let heightmapBrushPower: any;
	declare let imageConverter: any;
	declare let imageConverterPalette: any;
	declare let imageToLoad: any;
	declare let lim: AnyFn;
	declare let list: any;
	declare let loopSubdivision: any;
	declare let onMouseMove: AnyFn;
	declare let pickerH: LegacyControlElement;
	declare let pickerHEX: LegacyControlElement;
	declare let pickerHSL_H: LegacyControlElement;
	declare let pickerHSL_L: LegacyControlElement;
	declare let pickerHSL_S: LegacyControlElement;
	declare let pickerL: LegacyControlElement;
	declare let pickerRGB_B: LegacyControlElement;
	declare let pickerRGB_G: LegacyControlElement;
	declare let pickerRGB_R: LegacyControlElement;
	declare let pickerS: LegacyControlElement;
	declare let Pint: any;
	declare let polylabel: AnyFn;
	declare let provinceInfo: HTMLElement;
	declare let provinceNameEditor: HTMLElement;
	declare let provinceNameEditorCustomForm: any;
	declare let provinceNameEditorSelectForm: any;
	declare let provincesAdd: HTMLElement;
	declare let provincesBrush: any;
	declare let provincesEditorRefresh: any;
	declare let provincesFooter: HTMLElement;
	declare let provincesFooterArea: HTMLElement;
	declare let provincesFooterPopulation: HTMLElement;
	declare let provincesHeader: HTMLElement;
	declare let provincesTreeType: any;
	declare let rankCells: AnyFn;
	declare let regenerateEmblems: AnyFn;
	declare let regimentSelectorHeader: HTMLElement;
	declare let religionsAdd: HTMLElement;
	declare let religionsAutoChange: HTMLInputElement;
	declare let religionsEditorRefresh: any;
	declare let religionsFooter: HTMLElement;
	declare let renderOcean: any;
	declare let rescaleHigher: HTMLElement;
	declare let rescaleLower: HTMLElement;
	declare let rescaleModifier: any;
	declare let RgbQuant: any;
	declare let shiftCompass: AnyFn;
	declare let stateNameEditor: HTMLElement;
	declare let stateNameEditorCustomForm: any;
	declare let stateNameEditorSelectForm: any;
	declare let stateNameEditorFullRegenerate: any;
	declare let stateNameEditorUpdateLabel: any;
	declare let statesAdd: HTMLElement;
	declare let statesAutoChange: HTMLInputElement;
	declare let statesBrush: any;
	declare let statesEditorRefresh: any;
	declare let statesFooter: HTMLElement;
	declare let statesHeader: HTMLElement;
	declare let statesInfo: HTMLElement;
	declare let statesTreeType: any;
	declare let styleLegendBack: any;
	declare let styleLegendColItems: any;
	declare let styleLegendOpacity: any;
	declare let templateBody: HTMLElement;
	declare let templateToLoad: any;
	declare let throttle: AnyFn;
	declare let turnButtonOff: AnyFn;
	declare let zonesEditorRefresh: any;
	declare let color: AnyFn;
}

export {};
